### PR TITLE
Update nixos-infect to 5d8c2ed (changed 17.03 to 17.09)

### PR DESCRIPTION
**Pull request by mhsjlw**
I believe there should be a better way of doing this than syncing up with `nixos-infect` every once in a while. Especially since the Linode pull request now maintains it's own separate copy of `nixos-infect`. I'm open to suggestions

### CODE REVIEW

**Comment by GlennS** [comment]
Seems like a good point.

As a first step - and especially since I've made the mess worse - I could:

1. Document what I had to do to nixos-infect to make it work with Linode
2. Instead of maintaining a separate copy of the file, make it into a patch that you can apply to the Digital Ocean version

Would that be helpful?

**Comment by mhsjlw** [comment]
Yup, that sounds like an awesome idea

**Comment by rbvermaa** [comment]
Committed in e93ef69

**Comment by GlennS** [comment]
I will use this as the basis for updating my Linode pull request.

At present my patch looks like: https://pastebin.com/g2hQMnqA

But there is still some unknown problem that I need to debug.

**Comment by GlennS** [comment]
Looks like this was reverted? https://github.com/NixOS/nixops/commit/72109e508b660e7fedb33d1c908513f680937f42

**Comment by mhsjlw** [comment]
> Still need to test upgrade from 17.03 bootstrapped droplet

**Pull request closed without merging**
