### PR TITLE
Libvirt improvements

### PR DESCRIPTION
**Pull request by domenkozar**
Since `/var/lib/libvirt/dnsmasq/{0}.leases` doesn't exist on NixOS, I'd suggest we make a bugfix release.

cc @aszlig @rbvermaa

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @bosu

**Comment by domenkozar** [comment]
cc @bosu

**Comment by domenkozar** [comment]
Hold on - I'm seeing some trouble with IP retrieval.

**Comment by bosu** [comment]
Everything looks good to me. Feel free to commit once it is working properly.

Thanks!

**Comment by domenkozar** [comment]
Aha found the issue, it's https://github.com/NixOS/nixpkgs/issues/10101 again. This works, ready to merge.

**Pull request merged**
