### PR TITLE
doc: fix paths

### PR DESCRIPTION
**Pull request by teto**
Some xsl files got moved from nixos/doc to nixos/lib/make-options-doc

### CODE REVIEW

**Comment by jfroche** [comment]
works for me, thank you !

**Comment by teto** [comment]
what is blocking ? I would like to open up an other PR but not having this makes nixops unusable on unstable (as I am).

**Comment by domenkozar** [comment]
CI is faling, needs nixpkgs bump as well

**Comment by teto** [comment]
you mean in .travis.yml ?
What should I put here ?
`  - nix-build --quiet release.nix -A build.x86_64-linux -I nixpkgs=channel:nixos-19.03`

**Comment by domenkozar** [comment]
@rbvermaa do we want to target 19.03 with the next release as well?

**Comment by teto** [comment]
hum didn't realize my PR was based on master.
Nevertheless, the commit is still here https://github.com/teto/nixops/commit/78ea977bf083503dfa00f595d8451c779057dbd8 if someone wants to fix nixops.

**Comment by asymmetric** [comment]
@teto I think it t would be easier if you reset your master branch and reopened this, so we can merge it.

**Pull request closed without merging**
