### PR TITLE
modules: optionSet -> submodule

### PR DESCRIPTION
**Pull request by ericsagnes**
This replace `optionSet` usages by `submodule`. #545 

I am not very familiar with nixops codebase, so please review carefully the changes before merging. 

The tarball is building fine.

cc @domenkozar

### CODE REVIEW

**Comment by rbvermaa** [comment]
@domenkozar Is this compatible with at least 16.03?

**Comment by domenkozar** [comment]
Yes, `types.submodule` was there in 16.03

**Comment by rbvermaa** [comment]
Great, thanks!

**Comment by rbvermaa** [comment]
Hm, looks like this breaks on 16.03 deployments. I am considering reverting the change for now.

**Comment by domenkozar** [comment]
@rbvermaa can you provide more info how it breaks?

**Comment by rbvermaa** [comment]
All deployments seem to error out with:

    error: attribute ‘cipher’ missing, at /data/home/rob.vermaas/src/nixops/nix/ec2.nix:468:10
    (use ‘--show-trace’ to show detailed location information)
    error: evaluation of the deployment specification failed

**Comment by domenkozar** [comment]
@ericsagnes any ideas why its not recognized?

**Comment by rbvermaa** [comment]
Probably has to do with the same type changes, but they are not interchangable between old and new types (submodule vs optionSet).

**Comment by ericsagnes** [comment]
Sorry, I must have made a mistake somewhere.

@rbvermaa 

> All deployments seem to error out with:

Could you share a configuration file that triggers this error?

**Pull request merged**
