### PR TITLE
Fix container's deploy when used with keys.

### PR DESCRIPTION
**Pull request by jraygauthier**
Fundamentally there was this missing `self.set_common_state(defn)`
that wasn't called on `create` which is essential to retrieve
keys.

This should also fix an issue I had when `storeKeysOnMachine`
was not set explicitly which caused the keys not to be sent.

Attempted to fix the use of `stop`/`start` when there are keys.
There remain some underlying problem I couldn't understand yet.

### CODE REVIEW

**Comment by jraygauthier** [comment]
Can somebody tell me what's wrong with this patch? Does nobody use containers with secret
keys (e.g: pulling from a repository for example)? Anyway, if anybody uses secrets keys for
their amazon cloud or any other cloud, don't they need to test locally?

**Comment by hrdinka** [comment]
I can confirm this bug. Here is a minimal test:

```
{
  test =
    { ... }:
    {
      deployment.targetEnv = "container";
      deployment.container.host = "localhost";
      deployment.keys.password.text = "foobar";
    }; 
}
```

Nixops does never send the keys and `/run/keys` stays empty. When `keys.target` gets started on the machine its activation will freeze forever cause it waits for `/run/keys/done` to be existent. I'll test this patch ASAP.

**Comment by jraygauthier** [comment]
Re-applied and re-tested on top of latest.

**Comment by ip1981** [comment]
Maybe related to https://github.com/NixOS/nixops/pull/650#issuecomment-299140107

**Comment by domenkozar** [comment]
I've just merged https://github.com/NixOS/nixops/pull/804 that should fix this.

**Comment by jraygauthier** [comment]
@domenkozar I just tested and confirm #804 fixes the problem.

**Comment by jraygauthier** [comment]
Thanks for the merge!

**Pull request closed without merging**
