### PR TITLE
digital ocean: enp0s3 -> ens3

### PR DESCRIPTION
**Pull request by disassembler**
This addresses #742 although would break anything with older kernels with the enp0s3 device.

### CODE REVIEW

**Comment by Mic92** [comment]
could this be checked?

**Comment by rbvermaa** [comment]
Yeah, we should be able to set the name based on the NixOS version (system.nixosVersion), right?

**Comment by Mic92** [comment]
From my understanding this happens in ubuntu and not nixos? So checking `nixosVersion` should be not the correct solution.

**Comment by domenkozar** [comment]
It happens on digitalocean running nixos.

**Comment by coretemp** [comment]
Hard coding such constants seems to be a flawed approach requiring a ton of maintenance(they change scheme every few years). I have little doubt that there is a way to do these things dynamically and in a way that is only kernel dependent (e.g. Linux or FreeBSD) and not on a particular version. 

Perhaps it could be done in a platform independent way by using some cross-platform tools. 

Another thing I don't really like is that a PR is opened in which the word "breaks" occurs. OTOH, perhaps we should be happy that the disassembler took the time to improve something to the DigitalOcean user community. I suppose what it comes down to is whether it would constitute a net "improvement" (which is why it isn't merged yet). If breaking something means we don't merge it, we should just be honest about that and thank disassembler for the attempt and close the PR. I don't know what the correct response is, but having 5 people (including me) look at it, seems to be a waste of resources. One qualified reviewer is economically optimal according to research. While no money changes hands, there are such limits as time and attention.

I vote to close this PR, just to draw a line.

**Comment by grahamc** [comment]
Hello!

Thank you for this PR. 

In the past several months, some major changes have taken place in
NixOps:

1. Backends have been removed, preferring **a plugin-based architecture**.
   Here are some of them:
   
   - https://github.com/NixOS/nixops-aws
   - https://github.com/NixOS/nixops-hetzner
   - https://github.com/nix-community/nixops-vbox
   - https://github.com/nix-community/nixops-libvirtd
   - https://github.com/nix-community/nixops-datadog
   
2. NixOps Core has been updated to be **Python 3 only**, and at the
   same time, **MyPy type hints** have been added and are now strictly
   required during CI.

This is all accumulating in to what I hope will be a **NixOps 2.0
release**. There is a tracking issue for that:
https://github.com/NixOS/nixops/issues/1242 . It is possible that 
more core changes will be made to NixOps for this release, with a
focus on simplifying NixOps core and making it easier to use and work
on.

My hope is that by adding types and more thorough automated testing,
it will be **easier for contributors to make improvements**, and for
contributions like this one to merge in the future.

However, because of the major changes, it has become likely that this
PR cannot merge right now as it is. The backlog of now-unmergable PRs
makes it hard to see which ones are being kept up to date.

If you would like to see this merge, **please bring it up to date with
`master` and reopen it**. If the or mypy type checking fails, please
correct any issues and then reopen it. I will be looking primarily at
open PRs whose tests are all green. 

Thank you again for the work you've done here, I am sorry to be
closing it now.

Graham

**Pull request closed without merging**
