### PR TITLE
fix reference to obsolete `jobs`

### PR DESCRIPTION
**Pull request by globin**

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @rbvermaa

**Comment by manveru** [comment]
:+1:

**Comment by manveru** [comment]
There's another reference at https://github.com/NixOS/nixops/blob/c187e8731fc477b569ee51e7849aa3d76d650470/nix/ssh-tunnel.nix#L72 which needs fixing at least for deploy to virtualbox.

**Comment by globin** [comment]
Oh right missed that one, fixed now, thanks!

**Pull request merged**
