### PR TITLE
Delete all the providers (and use plugins instead)

### PR DESCRIPTION
**Pull request by grahamc**
This PR goes a bit crazy all at once and won't merge as-is, but bear with me!

I've deleted all the code to support anything that isn't the `none` target and other fundamentals, like ssh tunnels and ssh keys.

Why:

- 35/45 open PRs are for providers
- PRs to NixOps are slow to merge because...
- it is super important that the providers in the core are stable and work well because users depend on it, and would be really mad if a new provider broke their existing stuff
- for a lot of the providers people don't really know how they work or interact with other stuff
- it is hard to know how to add a new provider because everything is so tangled together
- it is hard to add a new provider because it has to be _in core_, see also merging PRs is hard ...

anyway, I've extracted out the AWS parts to https://github.com/grahamc/nixops-aws and check this out, it worked:

```
[nix-shell:~/projects/personal]$ ../nixops/result/bin/nixops deploy  
resource ‘whatever’ is obsolete
vpc-nixops..........> creating vpc under region us-east-1
vpc-nixops..........>  done
sg..................> creating EC2 security group ‘charon-40acc6ee-ab85-11e7-aa88-9cb6d0dc0ef3-sg’...
subnet-d............> creating subnet in vpc vpc-0de62277
subnet-e............> creating subnet in vpc vpc-0de62277
igw.................> creating internet gateway in region us-east-1
subnet-a............> creating subnet in vpc vpc-0de62277
sg..................> adding new rules to EC2 security group ‘charon-40acc6ee-ab85-11e7-aa88-9cb6d0dc0ef3-sg’...
subnet-c............> creating subnet in vpc vpc-0de62277
subnet-f............> creating subnet in vpc vpc-0de62277
subnet-b............> creating subnet in vpc vpc-0de62277
igw.................> attaching internet gateway igw-8ec0f6f6 to vpc vpc-0de62277
subnet-d............>  done
subnet-e............>  done
subnet-a............>  done
subnet-f............>  done
subnet-c............>  done
subnet-b............>  done
route-table.........> creating route table in vpc vpc-0de62277
association-subnet-f> associating route table rtb-25ed6d5a to subnet subnet-0a2f5a05
association-subnet-b> associating route table rtb-25ed6d5a to subnet subnet-ed857fd3
association-subnet-d> associating route table rtb-25ed6d5a to subnet subnet-a3ec5dff
association-subnet-a> associating route table rtb-25ed6d5a to subnet subnet-95fb4cf2
association-subnet-c> associating route table rtb-25ed6d5a to subnet subnet-f73a7ebd
association-subnet-e> associating route table rtb-25ed6d5a to subnet subnet-68a71446
igw-route...........> creating route igw-8ec0f6f6 => 0.0.0.0/0 in route table rtb-25ed6d5a


...

$ ../nixops/result/bin/nixops deploy  
resource ‘whatever’ is no longer obsolete
whatever............> creating EC2 instance (AMI ‘ami-d464cba9’, type ‘t2.nano’, region ‘us-east-1’)...
whatever............> waiting for IP address... [pending] [pending] [pending] [running] 52.3.248.35 / 10.0.36.121
whatever............> waiting for SSH..............................
whatever............> replacing temporary host key...
whatever............> setting state version to 18.03
building all machine configurations...
these derivations will be built:
  /nix/store/6m9wz6c2lzyz1520vp16587xf0sqdnn4-etc-hosts.drv
  /nix/store/ws9yhavp7qwac5hjzigdaxjqj7izpf85-unit-nscd.service.drv
  /nix/store/0251wv218w9zkx3yx1i6707qwr7pa7n5-system-units.drv

...

whatever............> starting the following units: apply-ec2-data.service, audit.service, kmod-static-nodes.service, network-local-commands.service, network-setup.service, nix-daemon.socket, nscd.service, print-host-key.service, rngd.service, systemd-journal-catalog-update.service, systemd-modules-load.service, systemd-sysctl.service, systemd-timesyncd.service, systemd-tmpfiles-clean.timer, systemd-tmpfiles-setup-dev.service, systemd-udev-trigger.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, systemd-update-done.service
whatever............> activation finished successfully
personal> deployment finished successfully




[nix-shell:~/projects/personal]$ ../nixops/result/bin/nixops deploy -k
resource ‘igw’ is obsolete
resource ‘subnet-a’ is obsolete
resource ‘subnet-b’ is obsolete
resource ‘subnet-c’ is obsolete
resource ‘subnet-d’ is obsolete
resource ‘subnet-e’ is obsolete
resource ‘subnet-f’ is obsolete
resource ‘nat-eip’ is obsolete
resource ‘association-subnet-d’ is obsolete
resource ‘association-subnet-e’ is obsolete
resource ‘vpc-nixops’ is obsolete
resource ‘association-subnet-b’ is obsolete
resource ‘association-subnet-c’ is obsolete
resource ‘igw-route’ is obsolete
resource ‘association-subnet-a’ is obsolete
resource ‘association-subnet-f’ is obsolete
resource ‘nat’ is obsolete
resource ‘route-table’ is obsolete
association-subnet-d> disassociating route table rtb-25ed6d5a from subnet subnet-a3ec5dff
association-subnet-e> disassociating route table rtb-25ed6d5a from subnet subnet-68a71446
association-subnet-b> disassociating route table rtb-25ed6d5a from subnet subnet-ed857fd3
association-subnet-c> disassociating route table rtb-25ed6d5a from subnet subnet-f73a7ebd
association-subnet-a> disassociating route table rtb-25ed6d5a from subnet subnet-95fb4cf2
association-subnet-f> disassociating route table rtb-25ed6d5a from subnet subnet-0a2f5a05
igw-route...........> deleting route to 0.0.0.0/0 from route table rtb-25ed6d5a
nat.................> deleting vpc NAT gateway nat-0d98ac70efd0c420d
igw.................> detaching internet gateway igw-8ec0f6f6 from vpc vpc-0de62277
route-table.........> deleting route table rtb-25ed6d5a
igw.................> got (possibly transient) EC2 error '{'Message': 'Network vpc-0de62277 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.', 'Code': 'DependencyViolation'}', retrying...
nat.................> waiting for nat gateway nat-0d98ac70efd0c420d to be deleted
nat.................> ......
igw.................> got (possibly transient) EC2 error '{'Message': 'Network vpc-0de62277 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.', 'Code': 'DependencyViolation'}', retrying...
nat.................> ......
igw.................> got (possibly transient) EC2 error '{'Message': 'Network vpc-0de62277 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.', 'Code': 'DependencyViolation'}', retrying...
nat.................> ........
igw.................> got (possibly transient) EC2 error '{'Message': 'Network vpc-0de62277 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.', 'Code': 'DependencyViolation'}', retrying...
nat.................> .........
igw.................> got (possibly transient) EC2 error '{'Message': 'Network vpc-0de62277 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.', 'Code': 'DependencyViolation'}', retrying...
nat.................> ...............
igw.................> got (possibly transient) EC2 error '{'Message': 'Network vpc-0de62277 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.', 'Code': 'DependencyViolation'}', retrying...
nat.................> ..... done
subnet-e............> deleting subnet subnet-68a71446

subnet-d............> deleting subnet subnet-a3ec5dff
subnet-a............> deleting subnet subnet-95fb4cf2
subnet-f............> deleting subnet subnet-0a2f5a05
subnet-c............> deleting subnet subnet-f73a7ebd
subnet-b............> deleting subnet subnet-ed857fd3
igw.................> deleting internet gateway igw-8ec0f6f6
vpc-nixops..........> destroying vpc vpc-0de62277...
nat-eip.............> releasing elastic IP 18.211.202.176
building all machine configurations...
ogden...............> copying closure...
zoidberg............> copying closure...
lord-nibbler........> copying closure...
```

Now, the AWS tests don't quite pass yet, and there are still kinks to work out -- but not so bad for a few hours of experimentation.

What say you, maintainers of NixOps?

Note, for a better view of the diff -- check this out:

https://github.com/NixOS/nixops/compare/8a365ceacd747706f490127001fa759f193c1621...grahamc:delete-the-code

and this, which is how the plugin hooks in: https://github.com/grahamc/nixops-aws/blob/cc54cac255a751d9831800e7864060917ffe099f/nixopsaws/plugin.py

cc @edolstra @rbvermaa @AmineChikhaoui 

ps this is just a demo and I'd imagine a nixopsWithPlugins thing.

### CODE REVIEW

**Comment by domenkozar** [comment]
After talking to Graham privately on IRC, here are my concerns:

- splitting repositories will yield more maintenance than it already needs for common backends (hetzner, aws, ??)
- it's probably a very good idea having clear api for backends and how to write one
- +1 for having docs that it's encouraged all new plugins should be separate projects

So with that in mind, I'd give commit access for existing backend maintainers, but if someone wishes to split their particular backend out, we can do that as well.

Also, we should probably get rid of tarball, since it makes patching nixops really annoying. /cc @cleverca22

**Comment by grahamc** [comment]
+1 for not actually deleting _most_ of the stuff from this repo, but I think it would be best if they all became plugins through the same API. _However_, I think the lesser-common resources _should_ be moved out of this repo. The DigitalOcean resources, for example barely work.

**Comment by grahamc** [comment]
Now that I got a :+1: from Eelco, it seems the truly hard part comes... moving all the providers in to plugins inside this repo :fraught_with_distress:. If anyone has any feedback, any at all, please leave it before I start down that dark path.

**Comment by zimbatm** [comment]
Would it make sense to create a nixops-providers org like terraform did?

**Comment by edolstra** [comment]
@zimbatm What would be the advantage over the nixos org?

**Comment by AmineChikhaoui** [comment]
I agree with the idea of having separate repositories for resources backends. I hope that will make maintenance easier and supporting other backends less dependent on the current list of people involved in NixOps.
We can probably take the opportunity and make docs better as well as the testing infrastructure which can be factored out of the main repo, but I guess that's not the main purpose of this PR but it's still nice to have :).

**Comment by zimbatm** [comment]
@edoltra: the main advantage that I see is that it would allow to be less strict about creating new repos in the new org since it's quite self-contained purpose wise. Everything in the nixos org is also often assumed to be maintained by more or less same set of people where here it could be different. And the last thing is that terraform did a similar thing ( https://github.com/terraform-providers/ ).

Those are not super strong arguments so that's why I asked.

Once the API is documented and opened up, it seems possible to me that we might be surprised by more unexpected contributions of plugins. If there is a clear place to put them that might help with the discovery and the idea that it's possible to contribute new plugins in the first place.

**Comment by flokli** [comment]
>  If anyone has any feedback, any at all, please leave it before I start down that dark path.

While designing the API, we should agree on one format to get configuration, not the mingle-mangle between xpath queries on the xml representation and `nixops.util.attr_property` that's currently present. I found that especially painful when taking a look at the libvirt provider.

Second thing (please bear with me if this goes too far), but can we save a lot of work, and get rid of a lot of code, by (ab)using Terraform to do all the dirty work of abstracting across multiple cloud providers?
I could imagine usecases like this:

 - a user describes infrastructure with Terraform, and uses a "nixos" provisioner pointing to a configuration. Of course, it would be necessary to pass parts of the terraform config into the system configuration, like the allocated IP address, region etc.
- a user uses Nix to "instantiate" Terraform resources/compose Terraform config, which then might be provisioned with above NixOS provider.

**Comment by coretemp** [comment]
@flokli Isn't that https://github.com/tweag/terraform-provider-nixos? (I was interested in that project, but I am not comfortable to use it if I am the only user.)

In any project, open-source or not, keeping quality PRs open for more than a week is a good way to reduce motivation for people to contribute. Compared to nixpkgs, nixops feels like abandonware, because of the glacial development speed. 

If the concern is that the quality of contributions is too low, one could specify that PRs need to come with automated tests of some kind. I can even imagine that you could build relations with the various cloud providers to make it possible to run such automated tests via some CI system. 

The model where everyone needs to ask for "permission" to get something included doesn't work well when a project is as inactive as this one. (Look at the history of Wikipedia.)

This PR is just a way to reduce scope of the project and thus solve the permission problem a bit. 

Namespaces could also work. I.e. `experimental.ec2.myfeature.enable = yes;` Iteration times are essentially too long. 

A similar argument holds for nixpkgs (number of PRs keeps growing and useful features have a too long delay before they are included). It's clear that nixpkgs is a success. It seems time to channel that success and *scale* it. I would like to see Nix leadership facilitate this.

**Pull request closed without merging**
