### PR TITLE
Create containers remotely when currentSystem != Linux

### LINKED ISSUE #398: Failure deploying containers from OS X
For example, with 

nixops create -d vbox-contain nixops/examples/trivial-container-in-vbox.nix
nixops deploy -d vbox-contain
# ..Build vbox machine..
machine> building initial configuration...
error: assertion failed at /nix/store/4han2qc1f181nw7f1bvf1an721xdb796-nixpkgs-16.03pre75806.77f8f35/nixpkgs/pkgs/os-specific/linux/kernel/generic.nix:31:1
(use ‘--show-trace’ to show detailed location information)
error: Command '['nix-build', '<nixpkgs/nixos>', '-A', 'system', '-I', 'nixos-config=/var/folders/lv/g1444dx54dz8q2tc2lk3vy8h0000gn/T/nixops-tmpgddZKk/machine-initial.nix', '-I', 'nixops=/nix/store/fiapphz7gkhiirm01f2bl8nzn6rd9350-nixops-1.3.1/share/nix/nixops']' returned non-zero exit status 1

I see that at an [backends/containers.py](https://github.com/NixOS/nixops/blob/e5fb3c50c8a259204b675337791edd67be32d9cb/nixops/backends/container.py#L140) an initial container config is built against builtins.currentSystem. I assume that's the cause of the error, or am I missing a trick somewhere? 

I've created a fork and branch that could avoid this but I'd like to check I'm not doing something dumb before I submit a PR. 

Thanks!

### PR DESCRIPTION
**Pull request by brocking**
Resolves #398

### CODE REVIEW

**Comment by gilligan** [comment]
I just ran into the same problem - @domenkozar could this be merged ?

**Comment by domenkozar** [comment]
Someone has to review the code and test it. I currently don't have time for it, sorry :/

**Comment by 3noch** [comment]
Any progress on this?

**Comment by johbo** [comment]
Just came across this issue. Just started to try this PR on my OSX box, so far it's working fine.

**Comment by yurrriq** [comment]
This didn't work for me when trying to deploy Digital Ocean or VirtualBox.

**Comment by johbo** [comment]
@yurrriq mind to share a few more details about your setup? 

On my end I think that things just worked because I did already have remote building set up, so the code which tries to auto-configure the remote machines was not hit in my case.

**Comment by yurrriq** [comment]
I've got remote building set up too via [nix-docker](https://github.com/lnl7/nix-docker) and I use [nix-darwin](https://github.com/lnl7/nix-darwin) to manage [my config](https://github.com/yurrriq/dotfiles/blob/374ec28f72bf5e6368afc4ddbd9d7932f435c869/darwin-configuration.nix#L270-L281).

**Comment by nick-b-h** [comment]
@yurrriq If the NIX_REMOTE_SYSTEMS variable is already set nixops won't amend it with the machines that it knows about. [1](https://github.com/NixOS/nixops/blob/21dc59f2294494024fd472d552033e372634ab55/nixops/deployment.py#L612) You will need to yourself add the details of the machines you want used for remote building to the file which that variable points to. 

On a more general note, I think the discussion in #260 has better solutions than what I attempted to resolve in this PR, because it relates to a slightly more general issue around nixops remote deployment. But when I opened this PR I didn't know about any of that discussion, and since it didn't attract much attention I thought I may as well leave it open. So if #260 is resolved this could be closed, but until then it may be helpful for it stay open for others to patch onto their nixops builds.

**Comment by betaboon** [comment]
I just stumbled upon this problem when deploying containers into a virtualbox from macos.

I just tested this PR:
- With a already working remote-build setup (configured using the nix-daemon plist) this solves the problem of not being able to deploy containers into a virtualbox from macos.
- With the remote-build setup disabled (so no remote-build settings in nix-daemon plist) this still fails.


As #260 hasn't progressed in almost a year, maybe we can progress on this PR?

**Comment by johbo** [comment]
Maybe we can split out a minimal change, in my case the change to `container.nix` does seem to do the trick already.

**Comment by johbo** [comment]
The changes in https://github.com/johbo/nixops/commit/64d1636344f352b32a98597711c16776cd4d941c did work fairly well in my case from darwin.

This would allow us to merge the good parts and leave the question regarding the moved chunk of python code open for the future. On my end I am not even so sure if we really should aim to automagically remote-build on the target machine. My bet is that we can live with a requirement that people on non-linux will have to set up remote building for nix in order to be able to use nixops on top of it.

As far as I understand the change, it does the following two bits:

1. Apply a default for `nixpkgs.system` also for the container backend.

2. In `container.py` there is a special twist: In `create` we first create a blank container and this one also needs to inherit the `nixpkgs.system` value. The whole magic around `eval_args` seems to address this problem.

Hope that's an alternative which makes it easier to merge in the needed parts. :)

**Comment by dhess** [comment]
Unless I've missed something, it appears that @johbo's nice patch (https://github.com/johbo/nixops/commit/64d1636344f352b32a98597711c16776cd4d941c) is no longer sufficient to build containers on macOS when using a recent `nixpkgs`. I've applied that patch to my own NixOps fork and when I try to build a container, I get a failure here:

https://github.com/NixOS/nixpkgs/blob/6ea4c3d335c9c7cf121125f41820bb00aa3043b2/pkgs/top-level/stage.nix#L154

So for some reason, NixOps is trying to evaluate `pkgsi686Linux` and I assume that, because the host platform is not Linux, this assertion is failing. I'm guessing this has something to do with the cross-compiling support not working properly with containers and remote builds from a Mac. (It's strange that a container built for an `x86_64-linux` would try to evaluate `pkgsi686Linux`, though, no?)

**Comment by grahamc** [comment]
Hello!

Thank you for this PR. 

In the past several months, some major changes have taken place in
NixOps:

1. Backends have been removed, preferring **a plugin-based architecture**.
   Here are some of them:
   
   - https://github.com/NixOS/nixops-aws
   - https://github.com/NixOS/nixops-hetzner
   - https://github.com/nix-community/nixops-vbox
   - https://github.com/nix-community/nixops-libvirtd
   - https://github.com/nix-community/nixops-datadog
   
2. NixOps Core has been updated to be **Python 3 only**, and at the
   same time, **MyPy type hints** have been added and are now strictly
   required during CI.

This is all accumulating in to what I hope will be a **NixOps 2.0
release**. There is a tracking issue for that:
https://github.com/NixOS/nixops/issues/1242 . It is possible that 
more core changes will be made to NixOps for this release, with a
focus on simplifying NixOps core and making it easier to use and work
on.

My hope is that by adding types and more thorough automated testing,
it will be **easier for contributors to make improvements**, and for
contributions like this one to merge in the future.

However, because of the major changes, it has become likely that this
PR cannot merge right now as it is. The backlog of now-unmergable PRs
makes it hard to see which ones are being kept up to date.

If you would like to see this merge, **please bring it up to date with
`master` and reopen it**. If the or mypy type checking fails, please
correct any issues and then reopen it. I will be looking primarily at
open PRs whose tests are all green. 

Thank you again for the work you've done here, I am sorry to be
closing it now.

Graham

**Pull request closed without merging**
