### PR TITLE
[WIP] Add vultr backend

### PR DESCRIPTION
**Pull request by disassembler**
addresses issue #575

### CODE REVIEW

**Comment by domenkozar** [comment]
Can you describe steps how to test the backend?

**Comment by disassembler** [comment]
I'll try to add documentation and tests this weekend. So far it's working great! Nixops is so much better than ansible/terraform for this use case.

**Comment by disassembler** [comment]
documentation and trivial example added. Still needs tests.

**Comment by 3noch** [comment]
So glad to see this getting some attention! Yay!

**Comment by dhess** [comment]
Hi, I pulled these 2 commits into my local tree, which is caught up with `master`. Installation works fine, but as soon as I reboot the instance, it fails to mount the root filesystem.

```
...
running udev...
starting device mapper and LVM...
Scanning for Btrfs filesystems
mounting /dev/vda1 on /...
mount: mounting /dev/vda1 on /mnt-root/ failed: Invalid argument

An error occurred in stage 1 of the boot process, which must mount the
root filesystem on `/mnt-root` and then start stage 2.  Press one
of the following keys:

   r) to reboot immediately
   *) to ignore the error and continue
```

Are you seeing this at all? I followed the steps outlined in https://www.vultr.com/docs/install-nixos-on-vultr, the only difference being that I used `ext4` rather than `btrfs` on the root filesystem.

**Comment by disassembler** [comment]
Yeah, btrfs is currently hard-coded in the backend python file (similar to ext4 being hard-coded in the digital ocean one). I need to mess around with it and see what would need done to move that into the config object instead. I'm looking at the libvirtd implementation of nixops to see how I could do that, but not making much progress.

**Comment by dhess** [comment]
Ahh, ok. Thanks for the clarification, I’ll try to work around this.

**Comment by wmertens** [comment]
Instead of the custom snapshot, wouldn't it be easier to use the smallest image they have and run https://github.com/jeaye/nixos-in-place on it? That would make using Vultr as simple as providing your credentials…

**Comment by pierrebeaucamp** [comment]
I agree that the best UX would be to only provide the credentials and let nixops worry about the rest. I wonder how hard it would be for nixops to create a snapchat on its own. But I would be more than happy to have a first version of vultr support in nixops, even if it would still require the manual steps.

**Comment by wmertens** [comment]
@pierrebeaucamp you're right, it shouldn't block inclusion. Once you have a snapshot you can basically use it forever.

I would like to see https://www.vultr.com/api/ mentioned on where to get the `dcid` and `vpsplanid` values. (funny, I just noticed you can't get the $2.5 sandbox plan via the API). Since you can only really get those values via the API, perhaps there could be a command to retrieve those values? I don't know if nixops allows custom commands like that… Perhaps get those values if they are missing from the description?

**Comment by grahamc** [comment]
Please do this in a plugin.

**Pull request closed without merging**
