### PR TITLE
support ipv6 for scp with "none" backend

### PR DESCRIPTION
**Pull request by phryneas**
Motivation:

Currently, secrets cannot be deployed when `deployment.targetHost` contains an ipv6.

This is because, while sshing to a ipv6 has the same syntax, `scp` requires square brackets around the ip. This adds square brackets for calls to scp around any ip with a colon.

I'm no python developer, so please take this PR with a grain of salt. Fortunately, it's not very big ;)

### CODE REVIEW

**Comment by phryneas** [comment]
Looks like another `get_ssh_name` is being called - I didn't account for the other backends. Are you definitely using the ǹone` backend?

**Comment by flokli** [comment]
I observed the regression with the hetzner provider, didn't test deploying secrets with the 'none' provider so far.

**Comment by phryneas** [comment]
Ah, okay, I need to update the signature to `def get_ssh_name(self, scp=False):` in the other providers, too, then.

I'll update this PR in the next days. In the meantime, just update `def get_ssh_name(self):` in the hetzner provider to `def get_ssh_name(self, scp=False):`, that should solve it for you for now.

**Comment by flokli** [comment]
> In the meantime, just update `def get_ssh_name(self):` in the hetzner provider to `def get_ssh_name(self, scp=False):`, that should solve it for you for now.

Looking at the other implementations of `get_ssh_name`, shouldn't the `[%s]` wrapping logic better be placed into a helper function in `nixops/backends/__init__.py`, used by both `upload_file` and `download_file`, instead of passing that `ssh` parameter through all backends, and applying logic there?

**Comment by phryneas** [comment]
Yup, I had the same thought. I'm quite busy right now, but I'll try to update this PR in the next weeks. It's not like it hasn't been lying around for a while already ;)

**Comment by flokli** [comment]
Sure, whenever you find the time :-)

**Comment by flokli** [comment]
@phryneas - poke, could you update this PR?

**Comment by phryneas** [comment]
@flokli oops, sorry. There you go.

**Comment by flokli** [comment]
LGTM.

CI is red due to the current nixpkgs breakage with azure-mgmt-compute-4.4.0 (unrelated, fixed by https://github.com/NixOS/nixpkgs/pull/56775).

**Pull request merged**
