### PR TITLE
deployment.py: fixup mistakes in #1346

### PR DESCRIPTION
**Pull request by grahamc**

### CODE REVIEW

**Comment by tewfik-ghariani** [comment]
Can we use 
```python
if dep._destroyed_event:
```
instead of 
```python
if dep._destroyed_event is not None:
```

As far as I remember, it improves slightly the performance and surely it's easier to read

**Comment by grahamc** [comment]
I think that is probably fine, what do you think @adisbladis?

**Comment by adisbladis** [comment]
@grahamc Fine by me, since it's `Optional[Event]` it's always truthy when set.

**Comment by grahamc** [comment]
Thanks, @tewfik-ghariani and @adisbladis?

**Pull request merged**
