### PR TITLE
ec2: Assign public ip by default

### PR DESCRIPTION
**Pull request by offlinehacker**
How else is instance able to access internet, except maybe if you are running deticated NAT instance.

### CODE REVIEW

**Comment by rbvermaa** [comment]
I am not sure if this is a good idea, what is the default behaviour in EC2 with regards to public IP assignment when starting instance in a VPC?

 Any other VPC users that have an option?

**Comment by danbst** [comment]
You can specify in Amazon VPC dashboard default behavior for public IPs.

**Comment by spinus** [comment]
I would vote -1 for public IP as default thing.

**Comment by domenkozar** [comment]
Seems like this one is a no-no.

**Comment by spinus** [comment]
@offlinehacker side comment, in AWS for example you have solution that you described, AWS has dedicated service to do NAT over private instances (or you can use VPN to your private network).

**Comment by offlinehacker** [comment]
Tnx, I know this now, I didn't know a year ago.

**Pull request closed without merging**
