### PR TITLE
Start with types rebase

### PR DESCRIPTION
**Pull request by TheWizardTower**
Let's try this again.

I think I vaporized my other branch, which nullified my existing PR. But. This is the same code.

### CODE REVIEW

**Comment by grahamc** [comment]
I wonder if that __future__ patch makes the nixops.deployment.Deployment type hint work, too. I've wanted to do that elsewhere but got bit by the circular dependency.

**Comment by TheWizardTower** [comment]
It looks like it passes mypy on my machine? No harm in giving it a go here.

**Comment by grahamc** [comment]
Blah. Dang. Burned by reality. Let's undo that and merge :)

**Comment by TheWizardTower** [comment]
```
ImportError: cannot import name 'Deployment' from 'nixops.deployment' (/build/nixops-1.8pre0_abcdef/nixops/deployment.py)
```

I think this is toast. :(

will un-merge.

**Comment by grahamc** [comment]
Thank you, this is amazing!

**Pull request merged**
