### PR TITLE
Upgrade to Python3

### PR DESCRIPTION
**Pull request by Taneb**
I haven't tested this executes properly but it passes all the tests on Linux.

There's a note in `nixops/diff.py` suggesting some improvements to the type declarations possible in python3 which I haven't dealt with.

### CODE REVIEW

**Comment by Taneb** [comment]
The CI failure seems to be unrelated to my PR, it looks like the nix Travis config now creates `/etc/nix` for us so when we try to do it in the `.travis.yml` pre-step it fails.

**Comment by lheckemann** [comment]
Did you use 2to3 for the syntactic/trivial changes? Why are they split into two commits?

As for the unit test target, I think it would be better to change `assert_merge` to compare `set(functools.reduce(…))` and `set(expect)` instead, to better encode that we don't guarantee an order.

**Comment by Taneb** [comment]
@lheckemann I did not use 2to3, the changes were manual. I agree with the solution to the test issue.

**Comment by grahamc** [comment]
I'm seeing a lot of failures around `.iteritems()` which should be `.items()` instead. Why not use 2to3?.

**Comment by grahamc** [comment]
It looks like the by-hand / partial conversion of deployment.py breaks 2to3.

**Comment by grahamc** [comment]
I did some more work on it here https://github.com/NixOS/nixops/compare/master...grahamc:python3 and make nixops info work, and nixops ssh-for-each work, but nixops deploy hangs forever with defunct ssh processes.

**Pull request closed without merging**
