### PR TITLE
network: Add nixpkgs attribute for passing custom nixpkgs

### PR DESCRIPTION
**Pull request by adisbladis**
This is useful to pin nixpkgs without flakes.

### CODE REVIEW

**Comment by cole-h** [comment]
Is using this as simple as setting `network.nixpkgs = sources.nixpkgs;` or something?

Would be nice if there were some docs to accompany this describing how to use it -- feel free to take inspiration from my suggestion over at https://github.com/NixOS/nixops/pull/1331.

**Comment by adisbladis** [comment]
An example of how to use this is:
```nix
{
  network.description = "Test deployment";
  network.nixpkgs = import <nixpkgs> {};

  myhost = { config, lib, resources, ... }: {};
}
```

**Comment by cole-h** [comment]
I fixed my previous issue with the following diff. However, note that it's very brittle -- it relies on `self.nix_exprs[0]` being the network file that has `network.nixpkgs` defined in order to get the nixpkgs path, in addition to preventing any other `-I nixpkgs=` flags from taking effect (because AFAICT the first of a flag wins over all the others). Now I can run `NIX_PATH= nixops deploy --dry-activate` and it works as expected! Another note is that `NIX_PATH= nixops deploy` without a `network.nixpkgs` defined fails as it did before.

```diff
diff --git a/nixops/deployment.py b/nixops/deployment.py
index b3ccb40f..bc389237 100644
--- a/nixops/deployment.py
+++ b/nixops/deployment.py
@@ -360,6 +360,18 @@ class Deployment:
             path for paths in get_plugin_manager().hook.nixexprs() for path in paths
         ]
 
+        nixpkgs_path = subprocess.run(
+            [
+                "nix-instantiate",
+                "--eval",
+                # FIXME: self.nix_exprs[0] is not guaranteed to always work
+                "-E" "(import {0}).network.nixpkgs.path".format(self.nix_exprs[0]),
+            ],
+            stdout=subprocess.PIPE,
+            stderr=subprocess.DEVNULL,
+            text=True,
+        ).stdout.rstrip()
+
         flags = (
             list(
                 itertools.chain(
@@ -371,6 +383,9 @@ class Deployment:
             )
             + self.extra_nix_flags
         )
+        flags.extend(
+            ["-I", "nixpkgs=" + nixpkgs_path] if nixpkgs_path is not "" else []
+        )
         flags.extend(["-I", "nixops=" + self.expr_path])
         return flags
 
```

**Comment by lovesegfault** [comment]
Is anything blocking this?

**Pull request merged**
