### PR TITLE
Remove some niche features

### PR DESCRIPTION
**Pull request by adisbladis**
See https://github.com/NixOS/nixops/issues/1242

Please note that this is _not_ about just removing these features. They will be reintroduced as plugins.

### CODE REVIEW

**Comment by grahamc** [comment]
Maybe we should make a repo for useful modules which also don't belong in nixpkgs, and refer to it in a changelog entry?

**Comment by grahamc** [comment]
really nice that they're not actually using any code in nixops itself, and the modules can just be dropped in

**Comment by grahamc** [comment]
LGTM but let's make that repo and move these expressions over. I asked in #nix-community on IRC about a good repo name for it. Once we do and move the exprs, let's make a link to it from the readme.

**Comment by grahamc** [comment]
I've split the history of auto-luks and auto-raid0 in to https://github.com/nix-community/nixos-modules-contrib. We probably should have been doing this from the start, but I'll add a changelog entry for this.

**Comment by adisbladis** [comment]
@grahamc I think we really need a story for how to get https://github.com/nix-community/nixos-modules-contrib into peoples NixOps deployments.
Imo we should make https://github.com/nix-community/nixos-modules-contrib a NixOps plugin.

**Comment by grahamc** [comment]
That sounds good to me. We might want to get the nixos-infect file a better home, too, while we're at it?

**Comment by adisbladis** [comment]
> That sounds good to me. We might want to get the nixos-infect file a better home, too, while we're at it?

Actually thinking about this a bit more I realised it doesn't make much sense to make the external repo a NixOps plugin as it's not directly tied to NixOps, it's just external NixOps modules.

So my recommendation to users in this instance would be to use [Niv](https://github.com/nmattia/niv), or at a later date Nix flakes.

**Comment by adisbladis** [comment]
`nixos-infect` already has another home at https://github.com/elitak/nixos-infect.
We may want to talk to @elitak and get this moved over to https://github.com/nix-community?

**Comment by grahamc** [comment]
I agree about not doing the plugin, and leaving that for other solutions like niv, flakes, or another mechanism. That said, if someone wanted to make the plugin, that would be great.

**Comment by grahamc** [comment]
Just did a rebase and trivial fix-up of including the 2.0 notes in the toc, and fixing header's underbars.

**Pull request merged**
