### PR TITLE
log more commands

### PR DESCRIPTION
**Pull request by teto**
while developing on nixops, I regularly have issues and logging the run command helps a lot in debugging.
I wonder if nixops should have different levels but it would be cool to better log commands. 
(I can remove the NIX_SSHOPTS)

### CODE REVIEW

**Comment by teto** [comment]
I have removed the controversial logging and logged an additionnal ssh command. Looking forward to see this merged.

**Comment by AmineChikhaoui** [comment]
I don't think emitting verbose logging by default is a good idea ? this should at least be done only if --debug is set imo.

**Comment by teto** [comment]
sure. Fixed.

**Comment by teto** [comment]
really addressed the comment this time.

**Pull request merged**
