### PR TITLE
Documentation about special NixOS module inputs

### PR DESCRIPTION
**Pull request by erictapen**
It took me more than a year to discover this feature. Maybe others won't need so long anymore with this PR...

@domenkozar Is that what you had in mind with #555?

### CODE REVIEW

**Comment by yorickvP** [comment]
Please fix the tabs/spaces ;)

**Comment by erictapen** [comment]
Oops, sorry for that. Is this what you wanted? Eventually need to fix my editor…

**Comment by yorickvP** [comment]
Looks good. @AmineChikhaoui ?

**Comment by AmineChikhaoui** [comment]
LGTM thanks !

**Comment by domenkozar** [comment]
Thank you!

**Comment by Chakerbh** [comment]
Just a quick note, that this only works across machines, if you want to use a machine attribute in a resource you need to use `resources.machines` instead.  140b2593 for example.

**Comment by erictapen** [comment]
Thanks for merging!
@Chakerbh Unfortunately I have no knowledge about this `resources` attribute, so I don't see myself adjusting the docs on that…

**Pull request merged**
