### PR TITLE
DO NOT MERGE: Nix 2 out of memory workaround

### PR DESCRIPTION
**Pull request by nh2**
This is a workaround for the `out of memory` issue introduced with Nix 2 and present in NixOS 18.03 images (e.g. NixOS 18.03 AMIs).

It includes my fix from https://github.com/NixOS/nix/pull/2206

## How to use this workaround

Use this branch and set

```
deployment.ec2.nixosAmiVersion = "17.09";
```

for your AWS machines.

That will ensure the machine gets initially deployed with 17.09 which doesn't have the memory problem, will then get nix 2 with my patch deployed, so that in no of the two states is the problem present.

---

This is probably not intended to be merged, at least not with the hard nix override in the second patch.

However, if we made that override an option, then we could merge this.

Right now this is just to present a publicly visible workaround for people to use, until there's an official `nix` release with the fix.

### CODE REVIEW

**Comment by AmineChikhaoui** [comment]
I was just testing t2.nano/t2.micro instances with `nix.package = pkgs.nixUnstable` (Nix 2.1) on NixOS 18.03 and it seems to work just fine :)

@nh2 I'm going to close this PR as it seems that it's probably not relevant anymore, please feel free to re-open if you think I missed anything. Thanks

**Comment by edolstra** [comment]
I don't think `nixosAmiVersion` solves the problem well because it only helps on the initial deployment. Any subsequent deployment will use Nix 2.0 from the new system, so it will have the same OOM issues.

However, I think `nixosAmiVersion` might be useful for other use cases, such as testing NixOS upgrades.

**Comment by AmineChikhaoui** [comment]
@nh2 Ok right, seems the expression that I have didn't reproduce the initial issue, I was under the impression t2.nano/micro won't work at all even with a minimal expression but I guess I need to add few "large" packages to trigger the issue.

**Comment by AmineChikhaoui** [comment]
and yeah most likely the issue will persist unless Nix is built and activated before copying the closure which doesn't happen.
Most likely we will need to wait for NixOS 18.09 to be officially released as I don't think shipping the ec2 AMIs with nixUnstable would be a good idea.

**Comment by nh2** [comment]
> Any subsequent deployment will use Nix 2.0 from the new system, so it will have the same OOM issues.

I don't understand this argument. The idea here is that `deployment.ec2.nixosAmiVersion` would always be used in combination with specifying a patched version of nix that doesn't have the issue.

The initial boot from AMI will bring up a version of nix that is so old that it doesn't have the problem. The first deployment will then instal whatever version of nix that I specify, which of course would have the patches in to fix the issue.

At no point would a 2.0 version without the issue patched be installed on the target system.

**Comment by coretemp** [comment]
Is this now obsolete? If so, please close this.

**Comment by nh2** [comment]
> Is this now obsolete? If so, please close this.

No (please read the thread, this was already asked and answered above).

**Comment by grahamc** [comment]
Hello!

Thank you for this PR. 

In the past several months, some major changes have taken place in
NixOps:

1. Backends have been removed, preferring **a plugin-based architecture**.
   Here are some of them:
   
   - https://github.com/NixOS/nixops-aws
   - https://github.com/NixOS/nixops-hetzner
   - https://github.com/nix-community/nixops-vbox
   - https://github.com/nix-community/nixops-libvirtd
   - https://github.com/nix-community/nixops-datadog
   
2. NixOps Core has been updated to be **Python 3 only**, and at the
   same time, **MyPy type hints** have been added and are now strictly
   required during CI.

This is all accumulating in to what I hope will be a **NixOps 2.0
release**. There is a tracking issue for that:
https://github.com/NixOS/nixops/issues/1242 . It is possible that 
more core changes will be made to NixOps for this release, with a
focus on simplifying NixOps core and making it easier to use and work
on.

My hope is that by adding types and more thorough automated testing,
it will be **easier for contributors to make improvements**, and for
contributions like this one to merge in the future.

However, because of the major changes, it has become likely that this
PR cannot merge right now as it is. The backlog of now-unmergable PRs
makes it hard to see which ones are being kept up to date.

If you would like to see this merge, **please bring it up to date with
`master` and reopen it**. If the or mypy type checking fails, please
correct any issues and then reopen it. I will be looking primarily at
open PRs whose tests are all green. 

Thank you again for the work you've done here, I am sorry to be
closing it now.

Graham

**Pull request closed without merging**
