### PR TITLE
filesystem options: fix use of deprecated mkOption { options = ...; }

### LINKED ISSUE #1086: nixops broken with master nixpkgs
nixos/nixpkgs@27982b408e465554b8831f492362bc87ed0ec02a seems to have broken nixops:

    error: 'mkOption' at /home/delroth/work/nixpkgs/lib/options.nix:30:5 called with unexpected argument 'options', at /nix/store/pslrp15wfmma1aj9m2f6vy6m6s12xp7v-nixops-1.6.1pre0_abcdef/share/nix/nixops/gce.nix:382:19

Looks like "options" support in mkOption got removed.

### PR DESCRIPTION
**Pull request by delroth**
nixos/nixpkgs@27982b408e465554b8831f492362bc87ed0ec02a removed it,
breaking nixops in the process. Migrate to the new recommended way of
enriching options.

Fixes #1086.

### CODE REVIEW

**Comment by teto** [comment]
solved it for me thanks \o/

**Comment by AmineChikhaoui** [comment]
thanks !

**Comment by delroth** [comment]
@AmineChikhaoui any thoughts to making a 1.6.2 (or 1.6.1.1 :) ) release with this included? 19.03 is coming very soon and nixops is currently unusable in it (19.03 packages 1.6.1, latest stable, but 1.6.1 doesn't work with 19.03). I've seen plenty of confusion on nixpkgs, #nixos, even #1086 on this repo.

**Comment by danbst** [comment]
@delroth I'm reverting my change, as it turned out to cause more harm than good.

**Comment by AmineChikhaoui** [comment]
@delroth Yes, I'm running the tests now and I'll then ask Rob to add a release

**Pull request merged**
