### PR TITLE
Convert libvirtd to use make-disk-image

### PR DESCRIPTION
**Pull request by clefru**
This fixes https://github.com/NixOS/nixops/issues/931 by reusing the
image builder of <nixpkgs/nixos/lib/make-disk-image.nix>. This image
builder produces nixos.qcow2 instead of disk.qcow2. This image is now
"baseless", so it obsoletes "qemu-img rebase". We can also remove our
special-case image builder libvirtd-image.nix as a whole.

### CODE REVIEW

**Comment by teto** [comment]
thanks for fixing this. The PR looks sound. I have a few trouble with my nixops setup at the moment but I will try to give it a run next week !

I am concerned abouyt the removal of  nix/libvirtd-image.nix . I have pending changes that make use of qemuGuest in libvirtd-image.nix . If this gets removed, where am I supposed to move the declaration

**Comment by clefru** [comment]
@teto Can you show me your modifications? I couldn't find them in your pull requests or in github.com/teto/nixops.

**Comment by teto** [comment]
for instance this line is new (the filename has changed but it's the same :  https://github.com/teto/nixops/blob/ad4c1866b88075bd6b28d2c9f4e39d74a8ca2027/nix/libvirtd/image.nix#L22).
It would be nice to keep having some libvirtd specific configuration ? even though this might be a bad example as it's useful outside libvirt, as soon as we use qemu in fact.

**Comment by clefru** [comment]
We already have libvirtd specific options even with this image builder. Just stick "services.qemuGuest.enable = true;" to the bottom of the file in libvirtd.nix inside the config set. The image builder will pick that up.

**Comment by teto** [comment]
this looks good, can we merge ?

**Comment by clefru** [comment]
From my point of view, yes :)

**Comment by teto** [comment]
Now that nixops  backends are implemented as plugins, you should reopen the PR against https://github.com/nix-community/nixops-libvirtd (I believe).

**Comment by clefru** [comment]
Meh, sorry. I don't feel like testing this again. I'll drop the PR entirely. and keep nixops as is locally.

**Pull request closed without merging**
