### PR TITLE
[WIP] Qemu agent

### PR DESCRIPTION
**Pull request by teto**
I do some testing on the TCP stack and in general to support static IP VMs etc it might be best to rely on the VM Agent.

The only missing part is the script to start the agent in the VM. There seems to be one at https://github.com/NixOS/nixpkgs/issues/34722 so I hope to  revisit this once it appears in nixpkgs.
Related issue https://github.com/NixOS/nixops/issues/847

### CODE REVIEW

**Comment by teto** [comment]
for whatever reason, I get plenty of errors like
```
File "/nix/store/dwd62qwwr4jzrcpp6nfrgq9mzrnjp73m-python2.7-libvirt-4.1.0/lib/python2.7/site-packages/libvirt.py", line 1347, in interfaceAddresses
    if ret is None: raise libvirtError ('virDomainInterfaceAddresses() failed', dom=self)
```
which I believe could be solved with the agent. I believe @mbrgm has a working agent ? do you intend to share it ? I would hate to duplicate the work :(

**Comment by mbrgm** [comment]
Yes, it's working and I intend to share it. However, it's based on #824 and I don't know how to handle this in a PR... Should I just put my branch on top of #824 (this is the current state), create a PR and then rebase whenever #824 changes?

**Comment by teto** [comment]
Sure you can open a PR prefixed with [WIP] (work in Progress) and rebase once #824 is merged. This prevents people from reimplementing things already being developed and let some users test it in advance. The dev activity is not that huge on nixops so it shouldn't be a burden. 
If you don't feel like opening a PR yet that's fine but I would love if possible to copy your code (I searched in your repo to no avail) since I've had tons of network problems when trying to do source routing xD

**Comment by teto** [comment]
sorry to nag you but may I ask when you intend to make it public ? I have a tight deadline so I might reimplement it myself (not like it's too much work) but I would rather improve what you have if need be.

**Comment by teto** [comment]
closing this as a better PR is on the way

**Pull request closed without merging**
