### PR TITLE
container: Block until destroy is complete. Fixes #809

### LINKED ISSUE #809: containers: Deploying after destroying makes nixops hang
When I use `targetEnv = "container";`, and `nixops destroy`, and then immediately `nixops deploy` again, nixops hangs at this output:

```
...
machine1.> creating container...
machine3..> creating container...
machine1.> host IP is 10.233.130.1, container IP is 10.233.130.2
machine3..> host IP is 10.233.131.1, container IP is 10.233.131.2
machine2> IP address is 10.233.122.2
machine2> setting state version to 17.09
^C
Traceback (most recent call last):
  File "./ops", line 130, in <module>
    env=env,
  File "/nix/store/k0c5spdm7g4lb9gkm3l20v81dbl93s0h-python3-3.6.3/lib/python3.6/subprocess.py", line 269, in call
    return p.wait(timeout=timeout)
  File "/nix/store/k0c5spdm7g4lb9gkm3l20v81dbl93s0h-python3-3.6.3/lib/python3.6/subprocess.py", line 1457, in wait
    (pid, sts) = self._try_wait(0)
  File "/nix/store/k0c5spdm7g4lb9gkm3l20v81dbl93s0h-python3-3.6.3/lib/python3.6/subprocess.py", line 1404, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

The `^C` is where I killed it with Ctrl+C because it hung forever.

The reason for this is that `nixos-container destroy`, which nixops calls, is asynchronous and exits immediately; thus for the next deploy, nixops and nixos-container think they can re-use existing container names that are actually still in use (they show up in `machinectl`).

See https://github.com/NixOS/nixpkgs/issues/32545

### PR DESCRIPTION
**Pull request by nh2**
Fix for #809, see commit message and added comments

### CODE REVIEW

**Comment by domenkozar** [comment]
@edolstra is there a better way?

**Comment by nh2** [comment]
> is there a better way?

@domenkozar This possibly: https://github.com/nh2/nixpkgs/commit/3a67fbbf2b7db4e6c3aab4b6d755bb6a12bed15c

**Comment by johbo** [comment]
@nh2 seems that we are chasing the same problems 😄 

I got inspired by your patch, ended up with a different code though. Found that both `destroy()` and `stop()` should wait until the operation is done. Interestingly the virualbox backend also has very similar code which waits until the state changes.

Here is my suggestion, it's based on existing code fragments which I found in the end of the file container.py: https://github.com/johbo/nixops/compare/0a5d91a...johbo:work-johbo

**Comment by johbo** [comment]
Noticed that comments are only possible in real PRs, created #825 for convenience.

**Comment by nh2** [comment]
@johbo My patch here was intended mainly as a workaround unles/until it gets fixed in `nixos-container` itself in https://github.com/NixOS/nixpkgs/pull/32992. Then nixops wouldn't need to have any of this logic.

**Comment by grahamc** [comment]
Hello!

Thank you for this PR. 

In the past several months, some major changes have taken place in
NixOps:

1. Backends have been removed, preferring **a plugin-based architecture**.
   Here are some of them:
   
   - https://github.com/NixOS/nixops-aws
   - https://github.com/NixOS/nixops-hetzner
   - https://github.com/nix-community/nixops-vbox
   - https://github.com/nix-community/nixops-libvirtd
   - https://github.com/nix-community/nixops-datadog
   
2. NixOps Core has been updated to be **Python 3 only**, and at the
   same time, **MyPy type hints** have been added and are now strictly
   required during CI.

This is all accumulating in to what I hope will be a **NixOps 2.0
release**. There is a tracking issue for that:
https://github.com/NixOS/nixops/issues/1242 . It is possible that 
more core changes will be made to NixOps for this release, with a
focus on simplifying NixOps core and making it easier to use and work
on.

My hope is that by adding types and more thorough automated testing,
it will be **easier for contributors to make improvements**, and for
contributions like this one to merge in the future.

However, because of the major changes, it has become likely that this
PR cannot merge right now as it is. The backlog of now-unmergable PRs
makes it hard to see which ones are being kept up to date.

If you would like to see this merge, **please bring it up to date with
`master` and reopen it**. If the or mypy type checking fails, please
correct any issues and then reopen it. I will be looking primarily at
open PRs whose tests are all green. 

Thank you again for the work you've done here, I am sorry to be
closing it now.

Graham

**Pull request closed without merging**
